/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tareapaint;

import java.awt.Color;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author gabrielmedinaelmcharrafille
 */
public class Vista extends javax.swing.JFrame {

    Modelo modelo = new Modelo();
    private boolean seleccionado = false;
    

    public boolean isSeleccionado() {
        System.out.println("Getter " + seleccionado);
        return seleccionado;
    }


    public void setSeleccionado(boolean seleccionado) {
            
        System.out.println("Setter " + seleccionado);
        this.seleccionado = seleccionado;
        isSeleccionado();
    }

    /**
     * Creates new form Vista
     */
    public Vista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        poligono = new javax.swing.JButton();
        numLados = new javax.swing.JComboBox<>();
        linea = new javax.swing.JButton();
        circulo = new javax.swing.JButton();
        lienzo = new java.awt.Canvas();
        guardar = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        poligono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/unselectPoli.png"))); // NOI18N
        poligono.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                poligonoMouseClicked(evt);
            }
        });
        poligono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poligonoActionPerformed(evt);
            }
        });

        numLados.setModel(new javax.swing.DefaultComboBoxModel<>(new Integer[] { 3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19 }));
        numLados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numLadosActionPerformed(evt);
            }
        });

        linea.setText("Linea");
        linea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lineaActionPerformed(evt);
            }
        });

        circulo.setText("Circulo");

        lienzo.setBackground(new java.awt.Color(255, 255, 255));

        guardar.setText("Guardar");
        guardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guardarMouseClicked(evt);
            }
        });
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(numLados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(linea)
                    .addComponent(circulo)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(guardar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(poligono)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(lienzo, javax.swing.GroupLayout.PREFERRED_SIZE, 890, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(poligono, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(numLados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(linea)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(circulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(guardar))
            .addComponent(lienzo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void poligonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poligonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_poligonoActionPerformed

    private void lineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lineaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lineaActionPerformed

    private void numLadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numLadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numLadosActionPerformed

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_guardarActionPerformed

    private void guardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guardarMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_guardarMouseClicked

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        String nombreArchivo = jTextField1.getText();
        // Llamar al método del modelo para insertar el nombre del archivo en la base de datos

    }//GEN-LAST:event_jTextField1ActionPerformed

    private void poligonoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_poligonoMouseClicked
        seleccionado = !seleccionado;
        Icon select = new ImageIcon(getClass().getResource("../images/selectPoli.png"));
        Icon Unselect = new ImageIcon(getClass().getResource("../images/unselectPoli.png"));
        setSeleccionado(seleccionado);
        if (seleccionado) {
            poligono.setSelected(true);
            poligono.setBackground(Color.BLUE); // Por ejemplo, cambiar el color de fondo a azul
            numLados.setEnabled(false);
            poligono.setIcon(Unselect);
        } else {
            poligono.setSelected(false);
            poligono.setBackground(Color.GRAY);
            numLados.setEnabled(true);
            poligono.setIcon(select);
          
        }
    }//GEN-LAST:event_poligonoMouseClicked
    public String obtenerNombreArchivo() {
        return jTextField1.getText();
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton circulo;
    public javax.swing.JButton guardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    public java.awt.Canvas lienzo;
    public javax.swing.JButton linea;
    public javax.swing.JComboBox<Integer> numLados;
    public javax.swing.JButton poligono;
    // End of variables declaration//GEN-END:variables
}
